#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ASCII Art Grass
const grassArt = `
🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱🌱
 \\  |  /   \\  |  /   \\  |  /   \\  |  /   \\  |  /   \\  |  /
  \\ | /     \\ | /     \\ | /     \\ | /     \\ | /     \\ | /
   \\|/       \\|/       \\|/       \\|/       \\|/       \\|/
════════════════════════════════════════════════════════════
             🌿 A S T R O T U R F   G R O W S 🌿
════════════════════════════════════════════════════════════

                  Welcome to the lawn maintenance
                     contribution generator!

                 Your grass is about to flourish...
`;

const grassTypes = [
  'Bermuda', 'Zoysia', 'Fescue', 'Kentucky Bluegrass', 'St. Augustine',
  'Centipede', 'Buffalo', 'Ryegrass', 'Dichondra', 'Bahia'
];

const grassActions = [
  'Mowing', 'Watering', 'Fertilizing', 'Aerating', 'Seeding',
  'Weeding', 'Edging', 'Mulching', 'Composting', 'Trimming'
];

const gardenTools = [
  'Lawnmower', 'Sprinkler', 'Rake', 'Hoe', 'Trowel',
  'Shears', 'Fertilizer spreader', 'Aerator', 'Edger', 'Watering can'
];

function generateGrassContent() {
  const actions = [
    () => createLawnCareTip(),
    () => createGrassFactFile(),
    () => createGardeningStory(),
    () => createToolGuide(),
    () => createSeasonalAdvice()
  ];

  const randomAction = actions[Math.floor(Math.random() * actions.length)];
  return randomAction();
}

function createLawnCareTip() {
  const grassType = grassTypes[Math.floor(Math.random() * grassTypes.length)];
  const action = grassActions[Math.floor(Math.random() * grassActions.length)];
  const filename = `docs/lawn-care-${action.toLowerCase()}-${Date.now()}.md`;

  const content = `# ${action} ${grassType} Grass

## Overview
Proper ${action.toLowerCase()} is essential for maintaining healthy ${grassType} grass throughout the growing season.

## Best Practices
- Monitor soil moisture levels regularly
- Apply techniques during optimal weather conditions
- Use appropriate tools for the task
- Follow seasonal guidelines for best results

## Tips
- ${grassType} grass responds well to consistent care
- Regular maintenance prevents major issues
- Timing is crucial for ${action.toLowerCase()} activities

*Generated by AstroTurf lawn care automation*
`;

  ensureDirectoryExists('docs');
  fs.writeFileSync(filename, content);
  return { filename, action: `Created ${action.toLowerCase()} guide for ${grassType} grass` };
}

function createGrassFactFile() {
  const grassType = grassTypes[Math.floor(Math.random() * grassTypes.length)];
  const filename = `guides/grass-facts-${grassType.toLowerCase().replace(' ', '-')}-${Date.now()}.md`;

  const content = `# ${grassType} Grass Facts

## Characteristics
${grassType} grass is known for its distinctive growth patterns and adaptability to various climates.

## Growing Conditions
- Soil type requirements vary by region
- Sunlight needs depend on seasonal factors
- Water requirements change throughout the year

## Maintenance Schedule
- Spring: Preparation and initial care
- Summer: Regular maintenance routines
- Fall: Preparation for dormancy
- Winter: Minimal intervention required

## Benefits
${grassType} provides excellent ground coverage and environmental benefits when properly maintained.

*Part of the AstroTurf botanical knowledge base*
`;

  ensureDirectoryExists('guides');
  fs.writeFileSync(filename, content);
  return { filename, action: `Added ${grassType} grass fact sheet` };
}

function createGardeningStory() {
  const tool = gardenTools[Math.floor(Math.random() * gardenTools.length)];
  const grassType = grassTypes[Math.floor(Math.random() * grassTypes.length)];
  const filename = `creative/garden-tale-${Date.now()}.md`;

  const content = `# The Tale of the ${tool}

In a suburban neighborhood where ${grassType} grass grew in perfect rows, there lived a gardener who understood the secret language of lawns.

Every morning, the ${tool.toLowerCase()} would gleam in the early sunlight, ready for another day of tending to the emerald carpet that stretched across the yard. The ${grassType} blades whispered stories of seasons past and dreams of growth yet to come.

"Today," thought the gardener, "we shall create something beautiful together."

The ${tool.toLowerCase()} hummed with purpose as it helped transform the ordinary yard into an extraordinary landscape. Each blade of grass stood a little taller, each edge a little sharper, each corner a little more defined.

By evening, the work was complete. The ${grassType} grass sparkled with dewdrops like tiny diamonds, and the gardener smiled, knowing that tomorrow would bring new opportunities to nurture this living green masterpiece.

*A story from the AstroTurf creative collection*
`;

  ensureDirectoryExists('creative');
  fs.writeFileSync(filename, content);
  return { filename, action: `Wrote gardening story featuring ${tool.toLowerCase()}` };
}

function createToolGuide() {
  const tool = gardenTools[Math.floor(Math.random() * gardenTools.length)];
  const filename = `tools/${tool.toLowerCase().replace(' ', '-')}-guide-${Date.now()}.md`;

  const content = `# ${tool} Maintenance Guide

## Purpose
The ${tool.toLowerCase()} is an essential tool for maintaining healthy grass and garden areas.

## Usage Instructions
1. Inspect the ${tool.toLowerCase()} before each use
2. Follow proper safety protocols
3. Apply appropriate techniques for best results
4. Clean and store properly after use

## Maintenance Tips
- Regular cleaning extends tool life
- Proper storage prevents damage
- Seasonal maintenance keeps tools in peak condition
- Quality tools make garden work more efficient

## Safety Considerations
Always prioritize safety when using garden tools and equipment.

*From the AstroTurf tool maintenance library*
`;

  ensureDirectoryExists('tools');
  fs.writeFileSync(filename, content);
  return { filename, action: `Created ${tool.toLowerCase()} maintenance guide` };
}

function createSeasonalAdvice() {
  const seasons = ['Spring', 'Summer', 'Fall', 'Winter'];
  const season = seasons[Math.floor(Math.random() * seasons.length)];
  const grassType = grassTypes[Math.floor(Math.random() * grassTypes.length)];
  const filename = `docs/seasonal-${season.toLowerCase()}-care-${Date.now()}.md`;

  const content = `# ${season} Lawn Care for ${grassType} Grass

## ${season} Overview
${season} brings unique opportunities and challenges for ${grassType} grass maintenance.

## Key Activities
- Monitor grass health indicators
- Adjust watering schedules appropriately
- Apply seasonal treatments as needed
- Prepare for upcoming season transitions

## ${season}-Specific Tips
- Temperature considerations affect growth patterns
- Seasonal weather patterns influence care routines
- Equipment needs may vary by season
- Planning ahead ensures optimal results

## Monthly Checklist
${season} care requires consistent attention to detail and proactive maintenance approaches.

*Seasonal guidance from AstroTurf experts*
`;

  ensureDirectoryExists('docs');
  fs.writeFileSync(filename, content);
  return { filename, action: `Added ${season.toLowerCase()} care guide for ${grassType} grass` };
}

function ensureDirectoryExists(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function commitChanges(result) {
  try {
    execSync('git add .', { stdio: 'pipe' });
    const commitMessage = `🌱 ${result.action}

Generated with AstroTurf automation
`;
    execSync(`git commit -m "${commitMessage}"`, { stdio: 'pipe' });
    return true;
  } catch (error) {
    return false;
  }
}

// Main execution
console.log(grassArt);

const result = generateGrassContent();
console.log(`✅ ${result.action}`);
console.log(`📁 Created: ${result.filename}`);

const committed = commitChanges(result);
if (committed) {
  console.log(`🎉 Changes committed successfully!`);
  console.log(`🌿 Your grass contribution is now growing in the repository!`);
} else {
  console.log(`📝 Files created (commit manually if desired)`);
}

console.log(`
🌱 Thank you for helping the AstroTurf garden flourish! 🌱`);